version: 2
registries:
  github:
    type: "maven-repository"
    url: "https://maven.pkg.github.com/pcalouche/spring-forge"
    username: "${{ secrets.GITHUB_ACTOR }}"
    password: "${{ secrets.GITHUB_TOKEN }}"
updates:
  - package-ecosystem: "maven"
    directory: "/"
    registries: "*"
    schedule:
      interval: "weekly"
    target-branch: "main"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"