version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    registries: "*"
    schedule:
      interval: "daily"
    target-branch: "main"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"